# Generated by Django 2.2.7 on 2020-01-14 16:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='filetype',
            new_name='fileupload',
        ),
    ]
