# Generated by Django 2.2.7 on 2020-01-15 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0002_auto_20200114_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='overall_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.FloatField()),
                ('negative', models.FloatField()),
                ('neutral', models.FloatField()),
                ('filename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentiment.fileupload')),
            ],
        ),
    ]
