# Generated by Django 2.2.7 on 2020-01-16 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sentiment', '0004_auto_20200116_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='overall_rating1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('positive', models.FloatField()),
                ('negative', models.FloatField()),
                ('neutral', models.FloatField()),
                ('filename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentiment.fileupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='overall_rating',
        ),
    ]
