# Generated by Django 2.2.7 on 2020-01-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0007_auto_20200116_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='overall_rating1',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
