# Generated by Django 2.2.7 on 2020-01-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0008_overall_rating1_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='individual_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('review_date', models.DateTimeField()),
                ('review_text', models.TextField()),
                ('process_review', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
                ('positive', models.FloatField()),
                ('negative', models.FloatField()),
                ('neutral', models.FloatField()),
            ],
        ),
    ]
