# Generated by Django 2.2.7 on 2020-01-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0009_individual_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_rating',
            name='review_date',
            field=models.DateField(),
        ),
    ]
