# Generated by Django 2.2.7 on 2020-01-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0010_auto_20200117_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='overall_rating1',
            name='rat',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
