# Generated by Django 2.2.7 on 2020-01-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0011_overall_rating1_rat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overall_rating1',
            name='rat',
            field=models.CharField(max_length=100),
        ),
    ]
