# Generated by Django 2.2.7 on 2020-01-17 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0013_auto_20200118_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_rating',
            name='filename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentiment.overall_rating'),
        ),
    ]
