# Generated by Django 2.2.7 on 2020-01-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0015_individual'),
    ]

    operations = [
        migrations.CreateModel(
            name='individual1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('review_text', models.TextField()),
                ('process_review', models.TextField()),
                ('positive', models.FloatField()),
                ('negative', models.FloatField()),
                ('neutral', models.FloatField()),
                ('rat', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='individual',
        ),
    ]
