# Generated by Django 2.2.7 on 2020-01-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0016_auto_20200118_0234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='individual1',
            new_name='individual',
        ),
    ]
